# frozen_string_literal: true

require_relative 'keymaps/emacs'

module FatTerm
  class  KeyMap
    MAP = {
      9 => KeyEvent.new(key: :tab),
      353 => KeyEvent.new(key: :backtab),
      265 => KeyEvent.new(key: :f1),
      277 => KeyEvent.new(key: :f1, shift: true),
      289 => KeyEvent.new(key: :f1, ctrl: true),
      301 => KeyEvent.new(key: :f1, shift: true, ctrl: true),
      313 => KeyEvent.new(key: :f1, meta: true),
      325 => KeyEvent.new(key: :f1, shift: true, meta: true),
      266 => KeyEvent.new(key: :f2),
      278 => KeyEvent.new(key: :f2, shift: true),
      290 => KeyEvent.new(key: :f2, ctrl: true),
      302 => KeyEvent.new(key: :f2, shift: true, ctrl: true),
      314 => KeyEvent.new(key: :f2, meta: true),
      326 => KeyEvent.new(key: :f2, shift: true, meta: true),
      267 => KeyEvent.new(key: :f3),
      279 => KeyEvent.new(key: :f3, shift: true),
      291 => KeyEvent.new(key: :f3, ctrl: true),
      303 => KeyEvent.new(key: :f3, shift: true, ctrl: true),
      315 => KeyEvent.new(key: :f3, meta: true),
      327 => KeyEvent.new(key: :f3, shift: true, meta: true),
      268 => KeyEvent.new(key: :f4),
      280 => KeyEvent.new(key: :f4, shift: true),
      292 => KeyEvent.new(key: :f4, ctrl: true),
      304 => KeyEvent.new(key: :f4, shift: true, ctrl: true),
      316 => KeyEvent.new(key: :f4, meta: true),
      328 => KeyEvent.new(key: :f4, shift: true, meta: true),
      269 => KeyEvent.new(key: :f5),
      281 => KeyEvent.new(key: :f5, shift: true),
      293 => KeyEvent.new(key: :f5, ctrl: true),
      305 => KeyEvent.new(key: :f5, shift: true, ctrl: true),
      317 => KeyEvent.new(key: :f5, meta: true),
      329 => KeyEvent.new(key: :f5, shift: true, meta: true),
      270 => KeyEvent.new(key: :f6),
      282 => KeyEvent.new(key: :f6, shift: true),
      294 => KeyEvent.new(key: :f6, ctrl: true),
      306 => KeyEvent.new(key: :f6, shift: true, ctrl: true),
      318 => KeyEvent.new(key: :f6, meta: true),
      # 330 duplicates the :delete key
      # 330 => KeyEvent.new(key: :f6, shift: true, meta: true),
      271 => KeyEvent.new(key: :f7),
      283 => KeyEvent.new(key: :f7, shift: true),
      295 => KeyEvent.new(key: :f7, ctrl: true),
      307 => KeyEvent.new(key: :f7, shift: true, ctrl: true),
      319 => KeyEvent.new(key: :f7, meta: true),
      # 331 duplicates the :insert key
      # 331 => KeyEvent.new(key: :f7, shift: true, meta: true),
      272 => KeyEvent.new(key: :f8),
      284 => KeyEvent.new(key: :f8, shift: true),
      296 => KeyEvent.new(key: :f8, ctrl: true),
      308 => KeyEvent.new(key: :f8, shift: true, ctrl: true),
      320 => KeyEvent.new(key: :f8, meta: true),
      332 => KeyEvent.new(key: :f8, shift: true, meta: true),
      273 => KeyEvent.new(key: :f9),
      285 => KeyEvent.new(key: :f9, shift: true),
      297 => KeyEvent.new(key: :f9, ctrl: true),
      309 => KeyEvent.new(key: :f9, shift: true, ctrl: true),
      321 => KeyEvent.new(key: :f9, meta: true),
      333 => KeyEvent.new(key: :f9, shift: true, meta: true),
      274 => KeyEvent.new(key: :f10),
      286 => KeyEvent.new(key: :f10, shift: true),
      298 => KeyEvent.new(key: :f10, ctrl: true),
      310 => KeyEvent.new(key: :f10, shift: true, ctrl: true),
      322 => KeyEvent.new(key: :f10, meta: true),
      334 => KeyEvent.new(key: :f10, shift: true, meta: true),
      275 => KeyEvent.new(key: :f11),
      287 => KeyEvent.new(key: :f11, shift: true),
      299 => KeyEvent.new(key: :f11, ctrl: true),
      311 => KeyEvent.new(key: :f11, shift: true, ctrl: true),
      323 => KeyEvent.new(key: :f11, meta: true),
      335 => KeyEvent.new(key: :f11, shift: true, meta: true),
      276 => KeyEvent.new(key: :f12),
      288 => KeyEvent.new(key: :f12, shift: true),
      300 => KeyEvent.new(key: :f12, ctrl: true),
      312 => KeyEvent.new(key: :f12, shift: true, ctrl: true),
      324 => KeyEvent.new(key: :f12, meta: true),
      # 336 duplicates the :down key
      # 336 => KeyEvent.new(key: :f12, shift: true, meta: true),

      331 => KeyEvent.new(key: :insert),
      392 => KeyEvent.new(key: :insert, shift: true),
      550 => KeyEvent.new(key: :insert, meta: true),
      551 => KeyEvent.new(key: :insert, shift: true, meta: true),
      552 => KeyEvent.new(key: :insert, ctrl: true),
      553 => KeyEvent.new(key: :insert, shift: true, ctrl: true),
      330 => KeyEvent.new(key: :delete),
      383 => KeyEvent.new(key: :delete, shift: true),
      531 => KeyEvent.new(key: :delete, meta: true),
      532 => KeyEvent.new(key: :delete, shift: true, meta: true),
      533 => KeyEvent.new(key: :delete, ctrl: true),
      534 => KeyEvent.new(key: :delete, shift: true, ctrl: true),
      262 => KeyEvent.new(key: :home),
      391 => KeyEvent.new(key: :home, shift: true),
      545 => KeyEvent.new(key: :home, meta: true),
      546 => KeyEvent.new(key: :home, shift: true, meta: true),
      547 => KeyEvent.new(key: :home, ctrl: true),
      548 => KeyEvent.new(key: :home, shift: true, ctrl: true),
      360 => KeyEvent.new(key: :end),
      386 => KeyEvent.new(key: :end, shift: true),
      540 => KeyEvent.new(key: :end, meta: true),
      541 => KeyEvent.new(key: :end, shift: true, meta: true),
      542 => KeyEvent.new(key: :end, ctrl: true),
      543 => KeyEvent.new(key: :end, shift: true, ctrl: true),
      339 => KeyEvent.new(key: :page_up),
      398 => KeyEvent.new(key: :page_up, shift: true),
      565 => KeyEvent.new(key: :page_up, meta: true),
      566 => KeyEvent.new(key: :page_up, shift: true, meta: true),
      567 => KeyEvent.new(key: :page_up, ctrl: true),
      568 => KeyEvent.new(key: :page_up, shift: true, ctrl: true),
      338 => KeyEvent.new(key: :page_down),
      396 => KeyEvent.new(key: :page_down, shift: true),
      560 => KeyEvent.new(key: :page_down, meta: true),
      561 => KeyEvent.new(key: :page_down, shift: true, meta: true),
      562 => KeyEvent.new(key: :page_down, ctrl: true),
      563 => KeyEvent.new(key: :page_down, shift: true, ctrl: true),

      258 => KeyEvent.new(key: :down),
      336 => KeyEvent.new(key: :down, shift: true),
      535 => KeyEvent.new(key: :down, meta: true),
      536 => KeyEvent.new(key: :down, shift: true, meta: true),
      537 => KeyEvent.new(key: :down, ctrl: true),
      538 => KeyEvent.new(key: :down, shift: true, ctrl: true),
      259 => KeyEvent.new(key: :up),
      337 => KeyEvent.new(key: :up, shift: true),
      576 => KeyEvent.new(key: :up, meta: true),
      577 => KeyEvent.new(key: :up, shift: true, meta: true),
      578 => KeyEvent.new(key: :up, ctrl: true),
      579 => KeyEvent.new(key: :up, shift: true, ctrl: true),
      260 => KeyEvent.new(key: :left),
      393 => KeyEvent.new(key: :left, shift: true),
      555 => KeyEvent.new(key: :left, meta: true),
      556 => KeyEvent.new(key: :left, shift: true, meta: true),
      557 => KeyEvent.new(key: :left, ctrl: true),
      558 => KeyEvent.new(key: :left, shift: true, ctrl: true),
      261 => KeyEvent.new(key: :right),
      402 => KeyEvent.new(key: :right, shift: true),
      570 => KeyEvent.new(key: :right, meta: true),
      571 => KeyEvent.new(key: :right, shift: true, meta: true),
      572 => KeyEvent.new(key: :right, ctrl: true),
      573 => KeyEvent.new(key: :right, shift: true, ctrl: true),
    }


    def initialize
      @bindings = {}
    end

    def bind(key:, ctrl: false, meta: false, shift: false, action: nil)
      @bindings[[key, ctrl, meta, shift]] = action
    end

    def resolve(event)
      return nil unless event

      @bindings[[event.key, event.ctrl?, event.meta?, event.shift?]]
    end
  end
end
